export enum SvgAttribute {
  COLOR = 'color',
  CX = 'cx',
  CY = 'cy',
  DISPLAY = 'display',
  DX = 'dx',
  DY = 'dy',
  FILL = 'fill',
  FILL_OPACITY = 'fill-opacity',
  HEIGHT = 'height',
  OPACITY = 'opacity',
  R = 'r',
  RX = 'rx',
  RY = 'ry',
  SCALE = 'scale',
  STROKE = 'stroke',
  VISIBILITY = 'visibility',
  WIDTH = 'width',
  X = 'x',
  Y = 'y',
}
